namespace MealMind.Modules.Nutrition.Application.Features.Commands.AddNutritionTargetCommand;

public record NutritionInPercentPayload(decimal ProteinPercentage, decimal CarbohydratesPercentage, decimal FatsPercentage);