// <auto-generated />
using System;
using MealMind.Modules.Identity.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MealMind.Modules.Identity.Infrastructure.Database.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    [Migration("20251112001304_AddsSubscriptionValueObject")]
    partial class AddsSubscriptionValueObject
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("identity")
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MealMind.Modules.Identity.Domain.IdentityUser.IdentityUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("IdentityUsers", "identity");
                });

            modelBuilder.Entity("MealMind.Modules.Identity.Domain.IdentityUser.IdentityUser", b =>
                {
                    b.OwnsOne("MealMind.Modules.Identity.Domain.IdentityUser.Subscription", "Subscription", b1 =>
                        {
                            b1.Property<Guid>("IdentityUserId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime?>("CanceledAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTime?>("CurrentPeriodEnd")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTime?>("CurrentPeriodStart")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("StripeCustomerId")
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)");

                            b1.Property<string>("StripeSubscriptionId")
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)");

                            b1.Property<DateTime?>("SubscriptionStartedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("SubscriptionStatus")
                                .HasColumnType("text");

                            b1.Property<string>("Tier")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("IdentityUserId");

                            b1.ToTable("Subscription", "identity");

                            b1.WithOwner()
                                .HasForeignKey("IdentityUserId");
                        });

                    b.Navigation("Subscription")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
