// <auto-generated />
using System;
using MealMind.Modules.AiChat.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace MealMind.Modules.AiChat.Infrastructure.Database.Migrations
{
    [DbContext(typeof(AiChatDbContext))]
    [Migration("20251212011600_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("aichat")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MealMind.Modules.AiChat.Domain.AiChatUser.AiChatUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("ActiveConversations")
                        .HasColumnType("integer");

                    b.Property<bool>("CanExportData")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanUseAdvancedPrompts")
                        .HasColumnType("boolean");

                    b.Property<int>("ConversationsLimit")
                        .HasColumnType("integer");

                    b.Property<int>("ConversationsMessagesHistoryDaysLimit")
                        .HasColumnType("integer");

                    b.Property<int>("DailyImageAnalysisLimit")
                        .HasColumnType("integer");

                    b.Property<int>("DailyPromptsLimit")
                        .HasColumnType("integer");

                    b.Property<int>("DocumentsLimit")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ImageAnalysisCorrectionPromptLimit")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("PromptTokensLimit")
                        .HasColumnType("integer");

                    b.Property<int>("ResponseTokensLimit")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AiChatUsers", "aichat");
                });

            modelBuilder.Entity("MealMind.Modules.AiChat.Domain.Conversation.AiChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ReplyToMessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId", "CreatedAt");

                    b.ToTable("ChatMessages", "aichat");
                });

            modelBuilder.Entity("MealMind.Modules.AiChat.Domain.Conversation.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "LastUsedAt");

                    b.ToTable("ChatConversations", "aichat");
                });

            modelBuilder.Entity("MealMind.Modules.AiChat.Domain.ImageAnalyze.ImageAnalyze", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("CaloriesMax")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CaloriesMin")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CarbsMax")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CarbsMin")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ConfidenceScore")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("FatMax")
                        .HasColumnType("numeric");

                    b.Property<decimal>("FatMin")
                        .HasColumnType("numeric");

                    b.Property<string>("FoodName")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<byte[]>("ImageBytes")
                        .HasColumnType("bytea");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Prompt")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<decimal>("ProteinMax")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ProteinMin")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("SavedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TotalQuantityInGrams")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("ImageAnalyze", "aichat");
                });

            modelBuilder.Entity("MealMind.Modules.AiChat.Domain.ImageAnalyze.ImageAnalyzeSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ImageAnalyzeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ImageAnalyzeId")
                        .IsUnique();

                    b.ToTable("ImageAnalyzeSessions", "aichat");
                });

            modelBuilder.Entity("MealMind.Modules.AiChat.Domain.Rag.ConversationDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AttachedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentGroupId")
                        .HasColumnType("uuid");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(1024)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("Embedding");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_cosine_ops" });

                    b.HasIndex("ConversationId", "DocumentGroupId", "ChunkIndex");

                    b.ToTable("ConversationDocuments", "aichat");
                });

            modelBuilder.Entity("MealMind.Modules.AiChat.Domain.Rag.RagDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AttachedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<Guid>("DocumentGroupId")
                        .HasColumnType("uuid");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(1024)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("Embedding");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_cosine_ops" });

                    b.HasIndex("DocumentGroupId", "ChunkIndex");

                    b.ToTable("RagDocuments", "aichat");
                });

            modelBuilder.Entity("MealMind.Modules.AiChat.Domain.Conversation.AiChatMessage", b =>
                {
                    b.HasOne("MealMind.Modules.AiChat.Domain.Conversation.Conversation", null)
                        .WithMany("ChatMessages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MealMind.Modules.AiChat.Domain.ImageAnalyze.ImageAnalyze", b =>
                {
                    b.HasOne("MealMind.Modules.AiChat.Domain.ImageAnalyze.ImageAnalyzeSession", null)
                        .WithMany("Corrections")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MealMind.Modules.AiChat.Domain.ImageAnalyze.ImageAnalyzeSession", b =>
                {
                    b.HasOne("MealMind.Modules.AiChat.Domain.ImageAnalyze.ImageAnalyze", "ImageAnalyze")
                        .WithOne()
                        .HasForeignKey("MealMind.Modules.AiChat.Domain.ImageAnalyze.ImageAnalyzeSession", "ImageAnalyzeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImageAnalyze");
                });

            modelBuilder.Entity("MealMind.Modules.AiChat.Domain.Conversation.Conversation", b =>
                {
                    b.Navigation("ChatMessages");
                });

            modelBuilder.Entity("MealMind.Modules.AiChat.Domain.ImageAnalyze.ImageAnalyzeSession", b =>
                {
                    b.Navigation("Corrections");
                });
#pragma warning restore 612, 618
        }
    }
}
