// <auto-generated />
using System;
using MealMind.Modules.Training.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MealMind.Modules.Training.Infrastructure.Database.Migrations
{
    [DbContext(typeof(TrainingDbContext))]
    [Migration("20260317230404_FixedTypo")]
    partial class FixedTypo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("training")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MealMind.Modules.Training.Domain.TrainingPlan.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsCustom")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MuscleGroup")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.ToTable("Exercise", "training");
                });

            modelBuilder.Entity("MealMind.Modules.Training.Domain.TrainingPlan.SessionExercise", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TrainingSessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TrainingSessionId");

                    b.ToTable("SessionExercise", "training");
                });

            modelBuilder.Entity("MealMind.Modules.Training.Domain.TrainingPlan.TrainingPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PlannedOn")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("TrainingPlan", "training");
                });

            modelBuilder.Entity("MealMind.Modules.Training.Domain.TrainingPlan.TrainingSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("TrainingPlanId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TrainingPlanId");

                    b.ToTable("TrainingSession", "training");
                });

            modelBuilder.Entity("MealMind.Modules.Training.Domain.TrainingPlan.SessionExercise", b =>
                {
                    b.HasOne("MealMind.Modules.Training.Domain.TrainingPlan.TrainingSession", null)
                        .WithMany("Exercises")
                        .HasForeignKey("TrainingSessionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("MealMind.Modules.Training.Domain.TrainingPlan.CardioDetails", "CardioDetails", b1 =>
                        {
                            b1.Property<Guid>("SessionExerciseId");

                            b1.Property<int?>("AverageHeartRate");

                            b1.Property<decimal?>("AverageSpeed");

                            b1.Property<int?>("CaloriesBurned");

                            b1.Property<int?>("CaloriesEstimated");

                            b1.Property<decimal?>("DistanceInKm");

                            b1.Property<int>("DurationInMinutes");

                            b1.Property<string>("Notes");

                            b1.HasKey("SessionExerciseId");

                            b1.ToTable("SessionExercise", "training");

                            b1.ToJson("CardioDetails");

                            b1.WithOwner()
                                .HasForeignKey("SessionExerciseId");
                        });

                    b.OwnsOne("MealMind.Modules.Training.Domain.TrainingPlan.StrengthDetails", "StrengthDetails", b1 =>
                        {
                            b1.Property<Guid>("SessionExerciseId");

                            b1.HasKey("SessionExerciseId");

                            b1.ToTable("SessionExercise", "training");

                            b1.ToJson("StrengthDetails");

                            b1.WithOwner()
                                .HasForeignKey("SessionExerciseId");

                            b1.OwnsMany("MealMind.Modules.Training.Domain.TrainingPlan.ExerciseSet", "Sets", b2 =>
                                {
                                    b2.Property<Guid>("StrengthDetailsSessionExerciseId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<int>("Repetitions");

                                    b2.Property<int?>("RestTimeInSeconds");

                                    b2.Property<int>("SetNumber");

                                    b2.Property<int>("SetType");

                                    b2.Property<decimal>("Weight");

                                    b2.HasKey("StrengthDetailsSessionExerciseId", "__synthesizedOrdinal");

                                    b2.ToTable("SessionExercise", "training");

                                    b2.WithOwner()
                                        .HasForeignKey("StrengthDetailsSessionExerciseId");
                                });

                            b1.Navigation("Sets");
                        });

                    b.Navigation("CardioDetails");

                    b.Navigation("StrengthDetails");
                });

            modelBuilder.Entity("MealMind.Modules.Training.Domain.TrainingPlan.TrainingSession", b =>
                {
                    b.HasOne("MealMind.Modules.Training.Domain.TrainingPlan.TrainingPlan", null)
                        .WithMany("Sessions")
                        .HasForeignKey("TrainingPlanId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MealMind.Modules.Training.Domain.TrainingPlan.TrainingPlan", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("MealMind.Modules.Training.Domain.TrainingPlan.TrainingSession", b =>
                {
                    b.Navigation("Exercises");
                });
#pragma warning restore 612, 618
        }
    }
}
